//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamiteStore.Service.Console.OrderService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderService.IOrder")]
    public interface IOrder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/GetOrderByKey", ReplyAction="http://tempuri.org/IOrder/GetOrderByKeyResponse")]
        DynamiteStore.DomainModel.Order GetOrderByKey(int orderid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/GetOrderDetailsByKey", ReplyAction="http://tempuri.org/IOrder/GetOrderDetailsByKeyResponse")]
        DynamiteStore.DomainModel.Order GetOrderDetailsByKey(int orderid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/AddUpdateOrders", ReplyAction="http://tempuri.org/IOrder/AddUpdateOrdersResponse")]
        void AddUpdateOrders(DynamiteStore.DomainModel.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrder/DeleteOrderByKey", ReplyAction="http://tempuri.org/IOrder/DeleteOrderByKeyResponse")]
        void DeleteOrderByKey(int orderid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderChannel : DynamiteStore.Service.Console.OrderService.IOrder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderClient : System.ServiceModel.ClientBase<DynamiteStore.Service.Console.OrderService.IOrder>, DynamiteStore.Service.Console.OrderService.IOrder {
        
        public OrderClient() {
        }
        
        public OrderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DynamiteStore.DomainModel.Order GetOrderByKey(int orderid) {
            return base.Channel.GetOrderByKey(orderid);
        }
        
        public DynamiteStore.DomainModel.Order GetOrderDetailsByKey(int orderid) {
            return base.Channel.GetOrderDetailsByKey(orderid);
        }
        
        public void AddUpdateOrders(DynamiteStore.DomainModel.Order order) {
            base.Channel.AddUpdateOrders(order);
        }
        
        public void DeleteOrderByKey(int orderid) {
            base.Channel.DeleteOrderByKey(orderid);
        }
    }
}
