//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamiteStore.Service.Console.CustomerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerService.ICustomer")]
    public interface ICustomer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/GetCustomerByKey", ReplyAction="http://tempuri.org/ICustomer/GetCustomerByKeyResponse")]
        DynamiteStore.DomainModel.Customer GetCustomerByKey(int customerid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/GetCustomerByName", ReplyAction="http://tempuri.org/ICustomer/GetCustomerByNameResponse")]
        DynamiteStore.DomainModel.Customer GetCustomerByName(string FirstName, string LastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/GetAllCustomers", ReplyAction="http://tempuri.org/ICustomer/GetAllCustomersResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DynamiteStore.DBObjectState.State))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DynamiteStore.DomainModel.Customer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DynamiteStore.DomainModel.Person))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DynamiteStore.DomainModel.Address[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DynamiteStore.DomainModel.Address))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DynamiteStore.DomainModel.Order[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DynamiteStore.DomainModel.Order))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DynamiteStore.DomainModel.LineItem[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DynamiteStore.DomainModel.LineItem))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DynamiteStore.DomainModel.Product))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DynamiteStore.DomainModel.Category))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DynamiteStore.DomainModel.Product[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DynamiteStore.DomainModel.ProductColor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DynamiteStore.DomainModel.Payment[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DynamiteStore.DomainModel.Payment))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DynamiteStore.DomainModel.Customer[]))]
        object GetAllCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/GetAllCustomersByName", ReplyAction="http://tempuri.org/ICustomer/GetAllCustomersByNameResponse")]
        DynamiteStore.DomainModel.Customer[] GetAllCustomersByName(string FirstName, string LastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/GetAllCustomersWhoHasOrders", ReplyAction="http://tempuri.org/ICustomer/GetAllCustomersWhoHasOrdersResponse")]
        DynamiteStore.DomainModel.Customer[] GetAllCustomersWhoHasOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/GetCustomerDetailsByKey", ReplyAction="http://tempuri.org/ICustomer/GetCustomerDetailsByKeyResponse")]
        DynamiteStore.DomainModel.Customer GetCustomerDetailsByKey(int customerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/AddUpdateCustomers", ReplyAction="http://tempuri.org/ICustomer/AddUpdateCustomersResponse")]
        void AddUpdateCustomers(DynamiteStore.DomainModel.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/DeleteCustomerByKey", ReplyAction="http://tempuri.org/ICustomer/DeleteCustomerByKeyResponse")]
        void DeleteCustomerByKey(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerChannel : DynamiteStore.Service.Console.CustomerService.ICustomer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerClient : System.ServiceModel.ClientBase<DynamiteStore.Service.Console.CustomerService.ICustomer>, DynamiteStore.Service.Console.CustomerService.ICustomer {
        
        public CustomerClient() {
        }
        
        public CustomerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DynamiteStore.DomainModel.Customer GetCustomerByKey(int customerid) {
            return base.Channel.GetCustomerByKey(customerid);
        }
        
        public DynamiteStore.DomainModel.Customer GetCustomerByName(string FirstName, string LastName) {
            return base.Channel.GetCustomerByName(FirstName, LastName);
        }
        
        public object GetAllCustomers() {
            return base.Channel.GetAllCustomers();
        }
        
        public DynamiteStore.DomainModel.Customer[] GetAllCustomersByName(string FirstName, string LastName) {
            return base.Channel.GetAllCustomersByName(FirstName, LastName);
        }
        
        public DynamiteStore.DomainModel.Customer[] GetAllCustomersWhoHasOrders() {
            return base.Channel.GetAllCustomersWhoHasOrders();
        }
        
        public DynamiteStore.DomainModel.Customer GetCustomerDetailsByKey(int customerId) {
            return base.Channel.GetCustomerDetailsByKey(customerId);
        }
        
        public void AddUpdateCustomers(DynamiteStore.DomainModel.Customer customer) {
            base.Channel.AddUpdateCustomers(customer);
        }
        
        public void DeleteCustomerByKey(int id) {
            base.Channel.DeleteCustomerByKey(id);
        }
    }
}
